### ISSUE TITLE
启动时获取 Volume 报错

### ISSUE THREAD

**Issue by x1ah** [Mellcap/MellPlayer#1]
在 MellPlayer/player.py 第 199 行首次获取音量报错，因为在并未对 `volume` 属性初始化，默认返回 None，之后的加减音量显示正常。

**Comment by Mellcap** [comment]
好的，我稍后检查一下，请问是在什么环境下呢，能把报错信息贴出来吗？

**Comment by x1ah** [comment]
@Mellcap 
Python3.5.2, 系统环境
![](http://ww1.sinaimg.cn/large/005NaGmtly1fdk19uawl1j30ha05cgly)
报错是乱的，将就看呢

![](http://ww1.sinaimg.cn/large/005NaGmtly1fdk14igl0ej31e60d7mz7)

试过将 `mellplayer/player.py` 第 266 行改为 `return self.volume or 0` 能解决，但是这样启动后音量默认就显示0了。应该在这里获取初始音量并返回。

**Comment by Mellcap** [comment]
修改了一下，我明天在docker上验证一下再把代码推上去😄

**Comment by x1ah** [comment]
@Mellcap ~

**Comment by Mellcap** [comment]
@x1ah 有空的话 mellplayer/player.py的43行加上 `self.volume = 100` 试试
![image](https://cloud.githubusercontent.com/assets/11872712/23831313/897b8874-0759-11e7-8c8a-732ffb422f0f.png)

**Comment by x1ah** [comment]
@Mellcap  如果直接初始化为 100 之后，每次启动便是显示 Volume 100%，这就跟我上面直接初始化为0一样的问题了，肯定不是最好的解决方法。这里应该初始化为系统音量的。

**Comment by Mellcap** [comment]
@x1ah mpv音量是和系统的音量相互独立的，在mac中的初始音量就是100。为了解决在linux中的初始化报错问题，我在player中初始化了一下，这样修改的话在linux中还会报错吗？

**Comment by x1ah** [comment]
@Mellcap 有报错的。
![](http://ww1.sinaimg.cn/large/005NaGmtly1fdkbglelf6j30ut07tta7)
可能由于系统平台不一样的原因？在 Linux 下的 mpv 初始音量不是 100% 的。每次启动的初始音量是受上一次启动/操作的影响，初始音量是上一次操作的结果。但是我不知道怎么样获取音量大小。而且如果是默认初始化为 100 的话在 Linux 下有这样的临时解决方法。在第一次调用 `get_volume()` 方法返回 100 即可，也就是我上面说的把 `get_score()` 返回值改成 `self.volume or 100`

**Comment by Mellcap** [comment]
@x1ah 好的，我好好调试一下，尽快给出个解决方案

**Comment by x1ah** [comment]
@Mellcap 辛苦~

**Comment by Mellcap** [comment]
@x1ah 目前最好的办法就是按照你说的给个初始值，已经推上去了，如果测试没问题的话我就release到pip上

**Comment by Mellcap** [comment]
已经 release 上去了，可以search到MellPlayer (0.1.1.2)后，执行下面的命令即可
```bash
pip3 install MellPlayer --upgrade
```
